apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    github.com/project-slug: gaussye/my-test-github-action 
    # github.com/project-slug: samgabrail/${{ values.name }}
  description: ${{ values.name }} running on AWS EKS cluster managed by Terraform
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
